---
- name: Add sshkey
  hosts: all
  gather_facts: False

  tasks:
    - authorized_key:
        user: semaphore
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/home/semaphore/.ssh/id_rsa.pub') }}"