---
- name: Add sshkey
  hosts: all
  gather_facts: False

  tasks:
    - authorized_key:
        # user: {{ item.user }}
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '~/.ssh/*.pub') }}"