---
- name: Generate .ssh/config for multiple hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Include var encrypted file
      include_vars: /home/semaphore/files/sshkey-vault.yaml

    - name: Ensure the .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      run_once: true

    - name: Generate .ssh/config file
      template:
        src: /home/semaphore/files/config-ssh.j2
        dest: "~/.ssh/config"
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      run_once: true

    - name: Ensure correct permissions on the private key
      file:
        path: "~/.ssh/id_rsa"
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      run_once: true
