---
- name: Generate .ssh/config for multiple hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Include var encrypted file
      include_vars: /home/semaphore/files/sshkey-vault.yaml

    - name: Set host-specific variables dynamically
      set_fact:
        host_specific_vars: "{{ host_vars[inventory_hostname] | default({}) }}"

    - name: Debug all host-specific variables
      debug:
        var: host_specific_vars

    # - name: Set host-specific variables for each host
    #   set_fact:
    #     ssh_hosts: "{{ ssh_hosts | default([]) + [{'name': inventory_hostname, 'ip': hostvars[inventory_hostname].ansible_host | default(inventory_hostname), 'user': hostvars[inventory_hostname].user }}"
    #   run_once: true

    # - name: Set host-specific variables dynamically
      # set_fact:
        # host_specific_vars: "{{ host_vars[inventory_hostname] | default({}) }}"
#
    # - name: Add host-specific information to a list
      # set_fact:
        # ssh_hosts: "{{ ssh_hosts | default([]) + [host_specific_vars] }}"

    - name: Ensure the .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ssh_hosts[0].user }}"
        group: "{{ ssh_hosts[0].user }}"
      run_once: true

    - name: Generate .ssh/config file
      template:
        src: config-ssh.j2
        dest: "~/.ssh/config"
        mode: '0600'
        owner: "{{ ssh_hosts[0].user }}"
        group: "{{ ssh_hosts[0].user }}"
      run_once: true

    - name: Ensure correct permissions on the private key
      file:
        path: "~/.ssh/id_rsa"
        mode: '0600'
        owner: "{{ ssh_hosts[0].user }}"
        group: "{{ ssh_hosts[0].user }}"
      run_once: true
