---
- name: Set up Docker postgres backups
  hosts: all
  # become: true
  # become_method: sudo
  # become_user: root
  gather_facts: true

  tasks:
    - name: Include var encrypted file
      include_vars: /home/semaphore/postgres-vault.yaml

    - name: Set host-specific variables
      set_fact:
        db_user: "{{ host_vars[inventory_hostname].db_user }}"
        db_pass: "{{ host_vars[inventory_hostname].db_pass }}"

    - name: Debug host-specific variables
      debug:
        msg:
          - "db_user: {{ db_user }}"
          - "db_pass: {{ db_pass }}"

    - name: Generate host-env file
      template:
        src: /home/semaphore/host-env.j2
        dest: "~/docker_postgres_backups/.env"
      vars:
        db_user: "{{ db_user }}"
        db_pass: "{{ db_pass }}"

    - name: Git clone private repo
      git:
        repo: git@github.com:CiclicaTeam/docker_postgres_backups.git
        dest: ~/docker_postgres_backups
        accept_hostkey: yes
        key_file: ~/.ssh/id_rsa

    - name: Set postgres_backup.sh as executable
      file:
        path: ~/docker_postgres_backups/postgres_backup.sh
        mode: '0755'

    - name: Set up cron job for postgres_backup.sh
      cron:
        name: "Postgres backup"
        user: "{{ cron_user }}"
        minute: "0"
        hour: "2"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/bin/bash {{ user_home }}/docker_postgres_backups/postgres_backup.sh"