---
- name: Set up Docker postgres backups
  hosts: all
  # become: true
  # become_method: sudo
  # become_user: root
  gather_facts: true
  vars_files:
    - postgres-vault.yaml

  tasks:
    #- name: Debug user and user_home variables
    #  debug:
    #    msg:
    #      - "user: {{ cron_user }}"
    #      - "user_home: {{ user_home }}"

    - name: Set host-specific variables
      set_fact:
        # db_host: "{{ host_vars[inventory_hostname].db_host }}"
        # db_pass: "{{ host_vars[inventory_hostname].db_pass }}"
        db_host: "{{ postgres-vault.db_host }}"
        db_pass: "{{ postgres-vault.db_pass }}"

    - name: Create .env file from template
      template:
        src: host-env.j2
        dest: "~/docker_postgres_backups/.env"
      vars:
        user_home: "/home/{{ user }}"

    - name: Git clone private repo
      git:
        repo: git@github.com:CiclicaTeam/docker_postgres_backups.git
        dest: ~/docker_postgres_backups
        accept_hostkey: yes
        key_file: ~/.ssh/id_rsa

    - name: Set postgres_backup.sh as executable
      file:
        path: ~/docker_postgres_backups/postgres_backup.sh
        mode: '0755'

    - name: Create .env file based on env vars
      template:
        src: ./postgres_env.jinja
        dest: ~/docker_postgres_backups/.env


    - name: Set up cron job for postgres_backup.sh
      cron:
        name: "Postgres backup"
        user: "{{ cron_user }}"
        minute: "0"
        hour: "2"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/bin/bash {{ user_home }}/docker_postgres_backups/postgres_backup.sh"