---
- name: Rsync backups from remote servers
  hosts: 10.8.0.114
  gather_facts: true
  tasks:
    - name: Include var encrypted file
      include_vars: /home/semaphore/files/sshkey-vault.yaml

    - name: Ensure specific backup directories exist
      file:
        path: "~/kopia/backups/{{ item.name }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop: "{{ ssh_hosts }}"

    - name: Rsync backups from remote servers
      synchronize:
        src: "/home/ciclica_admin/docker_postgres_backups/db_backup/"
        dest: "~/kopia/backups/{{ item.name }}/"
        mode: pull
        delete: no
        use_ssh_args: yes
      vars:
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.user }}"
      loop: "{{ ssh_hosts }}"
      register: rsync_result

    - name: Send Slack notification
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        body_format: json
        body:
          text: "Rsync completed {% if item.rc == 0 %}successfully{% else %}with errors{% endif %} from {{ item.item.name }} ({{ item.item.ip }}) to ~/kopia/backups/{{ item.item.name }}"
      loop: "{{ rsync_result.results }}"
      when: slack_webhook_url is defined

    - name: Display rsync results
      debug:
        msg: "Rsync for {{ item.item.name }} ({{ item.item.ip }}) {% if item.rc == 0 %}completed successfully{% else %}encountered an error{% endif %}"
      loop: "{{ rsync_result.results }}"