---
- name: Rsync backups from remote servers
  hosts: localhost
  gather_facts: false
  # vars_files:
  #   - rsync_vault.yml

  tasks:
    - name: Include var encrypted file
      include_vars: /home/semaphore/files/sshkey-vault.yaml

    - name: Ensure local backup directories exist
      file:
        path: "{{ local_backup_base }}/{{ item.name }}"
        state: directory
        mode: '0755'
      loop: "{{ ssh_hosts }}"

    - name: Rsync backups from remote servers
      synchronize:
        src: "{{ remote_path }}"
        dest: "{{ local_backup_base }}/{{ item.name }}"
        mode: pull
        delete: no
        rsync_opts:
          - "--archive"
          - "--verbose"
          - "--compress"
      delegate_to: "{{ item.ip }}"
      vars:
        ansible_user: "{{ item.user }}"
      loop: "{{ ssh_hosts }}"
      register: rsync_result

    - name: Send Slack notification
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        body_format: json
        body:
          text: "Rsync completed {% if item.rc == 0 %}successfully{% else %}with errors{% endif %} from {{ item.item.name }} ({{ item.item.ip }}) to {{ local_backup_base }}/{{ item.item.name }}"
      loop: "{{ rsync_result.results }}"
      when: slack_webhook_url is defined

    - name: Display rsync results
      debug:
        msg: "Rsync for {{ item.item.name }} ({{ item.item.ip }}) {% if item.rc == 0 %}completed successfully{% else %}encountered an error{% endif %}"
      loop: "{{ rsync_result.results }}"