---
- name: Setup Rsync Backup Script
  hosts: localhost
  gather_facts: false
  vars_files:
    - /home/semaphore/files/sshkey-vault.yaml
  vars:
    ssh_key_path: "/home/{{ ansible_user }}/.ssh_kopia/id_rsa"
    local_backup_base: "/home/{{ ansible_user }}/kopia/backups"
  tasks:
    - name: Generate rsync backup script from template
      template:
        src: /home/semaphore/files/rsync_script.j2
        dest: /home/{{ ansible_user }}/rsync_backup.sh
        mode: '0755'

    - name: Display generated script (for debugging)
      debug:
        msg: "{{ lookup('file', '/home/{{ ansible_user }}/rsync_backup.sh') }}"

