---
- name: Install core packages for lxc containers
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - ufw
          - unattended-upgrades
          - sudo
          - wireguard-tools
          - openresolv
          - openssh-server
          - htop
        update_cache: true

    # - name: Start guest qemu-guest-agent
      # ansible.builtin.service:
        # name: qemu-guest-agent
        # state: started
        # enabled: true
